# Generated by Django 5.0.6 on 2024-06-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0005_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
