# Generated by Django 5.0.6 on 2024-06-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0010_icono_interest_notificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacion',
            name='icono',
        ),
        migrations.DeleteModel(
            name='Icono',
        ),
        migrations.DeleteModel(
            name='Notificacion',
        ),
    ]
