# Generated by Django 5.0.6 on 2024-06-12 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0011_remove_notificacion_icono_delete_icono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='interest',
            new_name='interests',
        ),
    ]
