# Generated by Django 5.0.6 on 2024-06-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0012_rename_interest_interest_interests'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='icon',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('male', 'Male'), ('male', 'Male')], max_length=50, null=True),
        ),
    ]
