# Generated by Django 5.0.6 on 2024-06-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0013_interest_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interest',
            name='icon',
        ),
    ]
