# Generated by Django 5.0.6 on 2024-07-17 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0024_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.customer'),
        ),
        migrations.AddField(
            model_name='experience',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.customer'),
        ),
        migrations.AddField(
            model_name='interest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.customer'),
        ),
        migrations.AddField(
            model_name='language',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.customer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.customer'),
        ),
        migrations.AddField(
            model_name='skills',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.customer'),
        ),
        migrations.AlterField(
            model_name='person',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.customer'),
        ),
    ]
