# Generated by Django 5.0.6 on 2024-07-17 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0025_education_customer_experience_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='language',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='customer',
        ),
        migrations.AddField(
            model_name='education',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.person'),
        ),
        migrations.AddField(
            model_name='experience',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.person'),
        ),
        migrations.AddField(
            model_name='interest',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.person'),
        ),
        migrations.AddField(
            model_name='language',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.person'),
        ),
        migrations.AddField(
            model_name='profile',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.person'),
        ),
        migrations.AddField(
            model_name='skills',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.person'),
        ),
    ]
