# Generated by Django 5.0.6 on 2024-07-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0027_remove_education_person_remove_experience_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='customer',
        ),
    ]
