# Generated by Django 5.0.6 on 2024-07-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0029_person_user_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
