# Generated by Django 5.0.6 on 2024-07-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0042_person_customer_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='customer',
        ),
    ]
