# Generated by Django 5.0.6 on 2024-07-23 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0067_alter_education_user_alter_experience_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='experience',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='language',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='user',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='user',
        ),
        migrations.AddField(
            model_name='interest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
