# Generated by Django 5.0.6 on 2024-06-03 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0007_language_value_alter_skills_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='username',
        ),
    ]
