# Generated by Django 5.0.6 on 2024-06-19 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0016_alter_person_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='image',
            new_name='images',
        ),
    ]
