# Generated by Django 5.0.6 on 2024-06-19 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0017_rename_image_person_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='images',
            new_name='image',
        ),
    ]
