# Generated by Django 5.0.6 on 2024-06-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0019_rename_skill_person_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.CharField(max_length=255),
        ),
    ]
