# Generated by Django 5.0.6 on 2024-07-15 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0021_education_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myprofile.customer'),
        ),
    ]
