# Generated by Django 5.0.6 on 2024-07-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0026_remove_education_customer_remove_experience_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='person',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='person',
        ),
        migrations.RemoveField(
            model_name='interest',
            name='person',
        ),
        migrations.RemoveField(
            model_name='language',
            name='person',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='person',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='person',
        ),
    ]
