# Generated by Django 5.0.6 on 2024-07-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0039_person_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='user',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
