# Generated by Django 5.0.6 on 2024-07-18 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0040_rename_user_person_customer_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='customer',
        ),
    ]
