# Generated by Django 5.0.6 on 2024-07-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0045_customer_alter_person_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='customer',
        ),
    ]
