# Generated by Django 5.0.6 on 2024-07-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0046_remove_person_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myprofile.customer'),
        ),
    ]
