# Generated by Django 5.0.6 on 2024-07-22 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0050_education_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='person',
            new_name='user',
        ),
    ]
