# Generated by Django 5.0.6 on 2024-07-23 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0055_alter_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
    ]
