# Generated by Django 5.0.6 on 2024-07-23 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myprofile', '0065_education_name_alter_education_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='name',
        ),
    ]
